CC = g++
TARGET = TypeCasting.out
OBJS = TypeCasting.o
SRCS = TypeCasting.cpp

$(TARGET) : $(OBJS)
	$(CC) -o $@ $(OBJS)

$(OBJS) : $(SRCS)
	$(CC) -c -o $(OBJS) $(SRCS)

clean :
	rm $(TARGET)
	rm $(OBJS)
